'use strict';

// Browser worker for the source-controlled simulation.
importScripts('./engine/model.js', './engine/reference_kernel.js');

const E=['Water','Earth','Fire','Air'];
const P=[
 {code:'W',name:'Water',inputs:{Water:1},equipmentPrice:15000},
 {code:'E',name:'Earth',inputs:{Earth:1},equipmentPrice:15000},
 {code:'F',name:'Fire',inputs:{Fire:1},equipmentPrice:15000},
 {code:'A',name:'Air',inputs:{Air:1},equipmentPrice:15000},
 {code:'W+E',name:'AquaTerra',inputs:{Water:1,Earth:1},equipmentPrice:25000},
 {code:'W+F',name:'HydroFlame',inputs:{Water:1,Fire:1},equipmentPrice:25000},
 {code:'W+A',name:'AeroWater',inputs:{Water:1,Air:1},equipmentPrice:25000},
 {code:'E+F',name:'TerraFlame',inputs:{Earth:1,Fire:1},equipmentPrice:25000},
 {code:'E+A',name:'TerraAir',inputs:{Earth:1,Air:1},equipmentPrice:25000},
 {code:'F+A',name:'EmberWind',inputs:{Fire:1,Air:1},equipmentPrice:25000}
];
const PB=Object.fromEntries(P.map(p=>[p.code,p]));
const PI=Object.fromEntries(P.map((p,i)=>[p.code,i]));
const EI=Object.fromEntries(E.map((e,i)=>[e,i]));
const T1P=[
 {name:'Aqua Distribution Co.',product:'W'}, {name:'Terra Distribution Co.',product:'E'},
 {name:'Ember Distribution Co.',product:'F'}, {name:'Gale Distribution Co.',product:'A'},
 {name:'AquaTerra Industries',product:'W+E'}, {name:'AquaFlame Industries',product:'W+F'},
 {name:'AquaAir Industries',product:'W+A'}, {name:'TerraForge Industries',product:'E+F'},
 {name:'TerraWind Industries',product:'E+A'}, {name:'EmberWind Industries',product:'F+A'}
];
const T0P=[
 ['Raw Materials Corp.', ['Water', 'Earth', 'Fire', 'Air']],
 ['Elements Inc.', ['Water', 'Earth', 'Fire', 'Air']],
 ['The People\'s Pottery, Inc.', ['Water', 'Earth', 'Fire']],
 ['The Crystal Company, Inc.', ['Water', 'Earth', 'Air']],
 ['Mechanics & Masonry, Inc.', ['Water', 'Fire', 'Air']],
 ['Standard Metal, Inc.', ['Earth', 'Fire', 'Air']],
 ['The Mineral Co.', ['Water', 'Earth']],
 ['General Machinery, Inc.', ['Water', 'Fire']],
 ['ShowZone Inc.', ['Water', 'Air']],
 ['Unimind Corp., Inc.', ['Earth', 'Fire']],
 ['Sky Research, Inc.', ['Earth', 'Air']],
 ['The Oligarch', ['Fire', 'Air']],
 ['MAMA Water Corp.', ['Water']],
 ['Union Water Corp.', ['Water']],
 ['MAMA Earth Corp.', ['Earth']],
 ['Planetary Earth Corp.', ['Earth']],
 ['MAMA Fire Corp.', ['Fire']],
 ['Advanced Flame, Inc.', ['Fire']],
 ['MAMA Air Corp.', ['Air']],
 ['Standard Wind, Inc.', ['Air']]
].map((x,i)=>({id:i,name:x[0],elements:x[1]}));
const N0=20,N1=1000,N2=50000,NP=10,NE=4,BPP=5000,MONTH=30;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const complexity=code=>Object.keys(PB[code].inputs).length;
const demandFactor=(code,c)=>Math.pow(clamp(c.compoundDemandFactor,.01,1),Math.max(0,complexity(code)-1));
const markup=(code,c)=>c.markup+c.compoundMarkupPremium*Math.max(0,complexity(code)-1);
const chokeMult=(code,c)=>1+c.compoundReservationPremium*Math.max(0,complexity(code)-1);
const quantW=(x,floor=0)=>{if(!Number.isFinite(x))return x;const r=Math.round(x*1e5)/1e5;const fq=Math.ceil((floor-1e-12)*1e5)/1e5;return Math.max(r,fq)};
const quantR=(x,floor=0)=>{if(!Number.isFinite(x))return x;const r=Math.round(x*100)/100;const fq=Math.ceil((floor-1e-12)*100)/100;return Math.max(r,fq)};
const hashSeed=(seed,tick)=>{let x=((seed>>>0)^Math.imul((tick+1)>>>0,0x9E3779B1))>>>0;x=Math.imul(x^(x>>>16),0x85EBCA6B)>>>0;x=Math.imul(x^(x>>>13),0xC2B2AE35)>>>0;return(x^(x>>>16))>>>0};
class RNG{constructor(seed){this.s=(seed>>>0)||1}next(){let x=this.s;x^=x<<13;x^=x>>>17;x^=x<<5;this.s=x>>>0;return this.s/4294967296}uniform(a,b){return a+(b-a)*this.next()}}
const qDemand=(qmax,ref,p,eta)=>qmax>0&&ref>0&&p>=0&&eta>0?qmax/(1+Math.pow(p/ref,eta)):0;

let cfg,tick=0,month=0,running=false,mode='fixed',targetTPS=30,timer=null,W,sourceState={activeOrders:0,fulfilledOrders:0};
let equipment,eqBook,controller,online,playerPrices,initialBuyerCapacityDraw,initialBuyerChokeDraw,initialBuyerEta,selectedId=0,lastSnapshot=null;
let lastReportAt=0,lastReportTick=0;
let analyticsHistory=[];
let prevT0Inventory=new Float64Array(N0*4), prevT1Finished=new Float64Array(N1*NP), prevT1FinishedCohort=new Float64Array(N1*NP);
let tickStartT0Inventory=new Float64Array(N0*4), tickStartT1Finished=new Float64Array(N1*NP);
let lastTickT0Produced=new Float64Array(N0*4), lastTickT1Made=new Float64Array(N1*NP);
let watchedCompanies={T0:new Set(),T1:new Set()};
let workerStats={steps:0};

function defaultCfg(){return {seed:12345,dbar:1,theta:.15,sigma:.005,dmin:.7,dmax:1.4,capacity:10000,targetInventory:500000,maxInventory:1000000,baseCost:1,retailTargetInventory:5000,retailMaxInventory:10000,retailInitialCash:5000,basicEquipmentCapacity:200,compoundEquipmentCapacity:100,manufacturingCostPerUnit:.25,minWholesaleLot:1000,k:.35,alpha:.15,minMargin:.08,markup:.25,compoundMarkupPremium:.15,vmin:.90,vmax:1.50,demandQtyMin:1,demandQtyMax:10,elasticityMin:1,elasticityMax:2,compoundDemandFactor:.45,compoundReservationPremium:.45,taumin:.05,taumax:.2,reliabilityAlpha:.15,switchingStableBand:.025,buyersPerCompany:50,initialCash:1000000};}
function normalizeConfig(c){const d={...defaultCfg(),...c};d.maxInventory=Math.max(d.targetInventory,d.maxInventory);d.retailMaxInventory=Math.max(d.retailTargetInventory,d.retailMaxInventory);d.taumin=Math.min(d.taumin,d.taumax);d.taumax=Math.max(d.taumin,d.taumax);d.demandQtyMin=Math.max(1,Math.min(100,Math.floor(d.demandQtyMin)));d.demandQtyMax=Math.max(d.demandQtyMin,Math.min(100,Math.floor(d.demandQtyMax)));d.elasticityMin=Math.max(.05,Math.min(10,d.elasticityMin));d.elasticityMax=Math.max(d.elasticityMin,Math.min(10,d.elasticityMax));d.minWholesaleLot=Math.max(1,Math.floor(d.minWholesaleLot));d.basicEquipmentCapacity=Math.max(1,Math.floor(d.basicEquipmentCapacity));d.compoundEquipmentCapacity=Math.max(1,Math.floor(d.compoundEquipmentCapacity));d.wholesaleInventoryResponse=clamp(Number.isFinite(+d.wholesaleInventoryResponse)?+d.wholesaleInventoryResponse:.10,.01,.50);d.wholesalePriceSmoothing=clamp(Number.isFinite(+d.wholesalePriceSmoothing)?+d.wholesalePriceSmoothing:.10,.01,.50);d.wholesaleFundingCap=clamp(Number.isFinite(+d.wholesaleFundingCap)?+d.wholesaleFundingCap:.65,.05,.95);return d;}
function sourceViews(){return {difficulty:new Float64Array(4),t0Inv:new Float64Array(N0*4),t0Cash:new Float64Array(N0),t0Price:new Float64Array(N0*4),t0Cost:new Float64Array(N0*4),t0PrevPrice:new Float64Array(N0*4),t0Rel:new Float64Array(N0*4),t0Stability:new Float64Array(N0*4),t0Req:new Float64Array(4),t0Ful:new Float64Array(4),t0Sold:new Float64Array(N0*4),t0Revenue:new Float64Array(N0*4),raw:new Float64Array(N1*4),rawBasis:new Float64Array(N1*4),t1Cash:new Float64Array(N1),t1EqBook:new Float64Array(N1),t1Controller:new Uint8Array(N1),t1Operates:new Uint8Array(N1*10),t1Price:new Float64Array(N1*10),t1PrevPrice:new Float64Array(N1*10),t1PriceStability:new Float64Array(N1*10),t1Rel:new Float64Array(N1*10),t1UnitCost:new Float64Array(N1*10),t1Fin:new Float64Array(N1*10),t1FinBasis:new Float64Array(N1*10),t1SalesEMA:new Float64Array(N1*10),t1Sold:new Float64Array(N1*10),t1Rev:new Float64Array(N1*10),t1COGS:new Float64Array(N1*10),t1InputNeed:new Float64Array(N1*4),t1PurchaseReq:new Float64Array(N1*4),t1LastBuy:new Float64Array(N1*4),preferredWholesale:new Int32Array(N1*4),playerPrice:new Float64Array(N1*10),buyerPreferred:new Int32Array(N2),buyerQMax:new Float64Array(N2),buyerChoke:new Float64Array(N2),buyerEta:new Float64Array(N2),buyerLastQ:new Float64Array(N2),buyerEffectivePrice:new Float64Array(N2),buyerChosenSupplier:new Int32Array(N2),active:new Float64Array(NP),potential:new Float64Array(NP),fulfilled:new Float64Array(NP),priceLost:new Float64Array(NP),stockUnmet:new Float64Array(NP),t0RelAttempts:new Float64Array(N0*4),t0RelFulfilled:new Float64Array(N0*4),t0RelChecks:new Float64Array(N0*4),t0RelAvailable:new Float64Array(N0*4),t0RelPriceSum:new Float64Array(N0*4),t0RelPriceSamples:new Uint32Array(N0*4),t1RelAttempts:new Float64Array(N1*10),t1RelFulfilled:new Float64Array(N1*10),t1RelAvailChecks:new Float64Array(N1*10),t1RelAvailable:new Float64Array(N1*10),t1RelPriceSum:new Float64Array(N1*10),t1RelPriceSamples:new Uint32Array(N1*10)};}
function initEngine(){W=sourceViews();sourceState={activeOrders:0,fulfilledOrders:0};}
function reset(c){cfg=normalizeConfig(c);tick=0;month=0;running=false;analyticsHistory=[];prevT0Inventory.fill(0);prevT1Finished.fill(0);prevT1FinishedCohort.fill(0);tickStartT0Inventory.fill(0);tickStartT1Finished.fill(0);lastTickT0Produced.fill(0);lastTickT1Made.fill(0);self.Phase0ReferenceKernel.zero(W);W.difficulty.fill(cfg.dbar);W.t0Cash.fill(cfg.initialCash);W.t0Rel.fill(.5);W.t0Stability.fill(1);W.t0Req.fill(0);W.t0Ful.fill(0);W.t0PrevPrice.fill(NaN);W.t0Price.fill(NaN);W.t0Cost.fill(0);
 for(let i=0;i<N0;i++)for(let e=0;e<NE;e++)if((T0P[i].elements.includes(E[e]))){const idx=i*4+e;const cost=cfg.baseCost*cfg.dbar;W.t0Cost[idx]=cost;W.t0Price[idx]=quantW(cost*(1+cfg.markup));W.t0PrevPrice[idx]=W.t0Price[idx];}
 equipment=Array.from({length:N1},(_,id)=>[T1P[Math.floor(id/100)].product]);eqBook=new Float64Array(N1);controller=new Uint8Array(N1);online=new Uint8Array(N1);playerPrices=Array.from({length:N1},()=>({}));
 W.t1Cash.fill(cfg.retailInitialCash);W.t1EqBook.fill(0);W.t1Controller.fill(0);W.t1Operates.fill(0);W.t1Price.fill(NaN);W.t1PrevPrice.fill(NaN);W.t1PriceStability.fill(1);W.t1Rel.fill(0);W.t1UnitCost.fill(0);W.t1Fin.fill(0);W.t1FinBasis.fill(0);W.t1SalesEMA.fill(0);W.t1LastBuy.fill(NaN);W.preferredWholesale.fill(-1);W.playerPrice.fill(NaN);
 const initialW=new Float64Array(4);for(let e=0;e<4;e++){let sum=0,n=0;for(let i=0;i<N0;i++)if(T0P[i].elements.includes(E[e])){sum+=W.t0Price[i*4+e];n++;}initialW[e]=sum/n;}
 for(let id=0;id<N1;id++){const code=equipment[id][0],pi=PI[code],p=PB[code],eq=p.equipmentPrice,uc=Object.entries(p.inputs).reduce((s,[e,r])=>s+initialW[EI[e]]*r,0)+cfg.manufacturingCostPerUnit,price=quantR(uc*(1+markup(code,cfg)),uc*(1+cfg.minMargin));eqBook[id]=eq;W.t1EqBook[id]=eq;W.t1Operates[id*10+pi]=1;W.t1Rel[id*10+pi]=.5;W.t1UnitCost[id*10+pi]=uc;W.t1Price[id*10+pi]=price;W.t1PrevPrice[id*10+pi]=price;}
 for(let id=0;id<N1;id++){for(let e=0;e<NE;e++){let best=-1,bp=Infinity;for(let s=0;s<N0;s++)if(T0P[s].elements.includes(E[e])){const p=W.t0Price[s*4+e];if(p<bp-1e-12||(Math.abs(p-bp)<=1e-12&&s<best)){best=s;bp=p;}}W.preferredWholesale[id*4+e]=best;}}
 initialBuyerCapacityDraw=new Float64Array(N2);initialBuyerChokeDraw=new Float64Array(N2);initialBuyerEta=new Float64Array(N2);const br=new RNG(hashSeed(cfg.seed,202));W.buyerPreferred.fill(0);W.buyerQMax.fill(0);W.buyerChoke.fill(0);W.buyerEta.fill(0);W.buyerLastQ.fill(0);W.buyerEffectivePrice.fill(NaN);W.buyerChosenSupplier.fill(0);
 for(let id=0;id<N2;id++){const home=Math.floor(id/cfg.buyersPerCompany),code=T1P[Math.floor(home/100)].product,pi=PI[code],anchor=W.t1Price[home*10+pi]||1;const cap=br.uniform(cfg.demandQtyMin,cfg.demandQtyMax),cd=br.uniform(cfg.vmin,cfg.vmax),eta=br.uniform(cfg.elasticityMin,cfg.elasticityMax);initialBuyerCapacityDraw[id]=cap;initialBuyerChokeDraw[id]=cd;initialBuyerEta[id]=eta;const qmax=Math.max(0,Math.round(cap*demandFactor(code,cfg)));const choke=clamp(anchor*cd*chokeMult(code,cfg),.01,10);W.buyerPreferred[id]=home;W.buyerQMax[id]=qmax;W.buyerChoke[id]=choke;W.buyerEta[id]=eta;const expected=qDemand(qmax,choke,anchor,eta);const base=Math.floor(expected),frac=expected-base,draw=hashSeed(cfg.seed,700000+id)/4294967296;
const initialQ=Math.max(0,Math.min(qmax,base+(draw<frac?1:0)));
salesEMAAdd(home*10+pi,initialQ); }
 lastReportAt=performance.now();lastReportTick=0;workerStats.steps=0;publish();}
function salesEMAAdd(idx,v){W.t1SalesEMA[idx]+=v;}
function updateLive(c){cfg=normalizeConfig({...cfg,...c});for(let id=0;id<N2;id++){const home=Math.floor(id/cfg.buyersPerCompany),code=T1P[Math.floor(home/100)].product,pi=PI[code],anchor=W.t1Price[home*10+pi]||1;const qmax=Math.max(0,Math.round(clamp(initialBuyerCapacityDraw[id],cfg.demandQtyMin,cfg.demandQtyMax)*demandFactor(code,cfg)));W.buyerQMax[id]=qmax;W.buyerChoke[id]=clamp(anchor*clamp(initialBuyerChokeDraw[id],cfg.vmin,cfg.vmax)*chokeMult(code,cfg),.01,10);W.buyerEta[id]=clamp(initialBuyerEta[id],cfg.elasticityMin,cfg.elasticityMax);}}
function rawSum(id){const b=id*4;return W.raw[b]+W.raw[b+1]+W.raw[b+2]+W.raw[b+3]}
function finSum(id){const b=id*10;let s=0;for(let p=0;p<NP;p++)if(W.t1Operates[b+p])s+=W.t1Fin[b+p];return s}
function wholesaleFundingRates(){const price=marketAverages().wP,funded=[0,0,0,0],requested=[0,0,0,0];for(let id=0;id<N1;id++){let spend=0;for(let e=0;e<NE;e++)spend+=(W.t1PurchaseReq[id*NE+e]||0)*(price[e]||cfg.baseCost);if(spend<=0)continue;const budget=Math.max(0,W.t1Cash[id]||0),share=Math.min(1,budget/spend);for(let e=0;e<NE;e++){const q=W.t1PurchaseReq[id*NE+e]||0;requested[e]+=q;funded[e]+=q*share;}}return {funded,requested,rates:requested.map((q,e)=>q>0?clamp(funded[e]/q,0,1):1)};}
function applyWholesaleStabilizer(){const target=Math.max(1,cfg.targetInventory),fund=wholesaleFundingRates();for(let e=0;e<NE;e++){let marketInventory=0,n=0;for(let id=0;id<N0;id++){const idx=id*NE+e;if(Number.isFinite(W.t0Price[idx])){marketInventory+=W.t0Inv[idx]||0;n++;}}if(!n)continue;const pressure=clamp((target-marketInventory)/target,-1,1);let targetRatio=clamp(1+cfg.markup+cfg.wholesaleInventoryResponse*pressure,cfg.vmin,cfg.vmax);
// When inventory is already ample, an unfunded order backlog is not a reason to raise price.
if(marketInventory>=target*.75&&fund.rates[e]<cfg.wholesaleFundingCap)targetRatio=Math.min(targetRatio,1+cfg.markup);
for(let id=0;id<N0;id++){const idx=id*NE+e;if(!Number.isFinite(W.t0Price[idx]))continue;const cost=Math.max(.000001,W.t0Cost[idx]||cfg.baseCost);const oldRatio=clamp(W.t0Price[idx]/cost,cfg.vmin,cfg.vmax);const smoothed=clamp(oldRatio*(1-cfg.wholesalePriceSmoothing)+targetRatio*cfg.wholesalePriceSmoothing,cfg.vmin,cfg.vmax);W.t0Price[idx]=quantW(cost*smoothed,cost*cfg.vmin);}}}
function step(){const t=tick+1;tickStartT0Inventory.set(W.t0Inv);tickStartT1Finished.set(W.t1Fin);self.Phase0ReferenceKernel.tick({W,cfg,tick:t,products:P,profiles:T0P,state:sourceState});for(let i=0;i<N0;i++)for(let e=0;e<NE;e++){const idx=i*NE+e;lastTickT0Produced[idx]=Math.max(0,(W.t0Inv[idx]||0)-(tickStartT0Inventory[idx]||0))+(W.t0Sold[idx]||0);}for(let id=0;id<N1;id++)for(let p=0;p<NP;p++){const idx=id*NP+p;lastTickT1Made[idx]=Math.max(0,(W.t1Fin[idx]||0)-(tickStartT1Finished[idx]||0))+(W.t1Sold[idx]||0);}tick=t;month=Math.floor(t/MONTH);workerStats.steps++;}
function marketAverages(){const wVol=[0,0,0,0],wRev=[0,0,0,0],rVol=new Float64Array(10),rRev=new Float64Array(10),rCounts=new Uint16Array(10);for(let i=0;i<N0;i++)for(let e=0;e<4;e++)if(T0P[i].elements.includes(E[e])){const idx=i*4+e;wVol[e]+=W.t0Sold[idx];wRev[e]+=W.t0Revenue[idx];}for(let id=0;id<N1;id++)for(let p=0;p<NP;p++)if(W.t1Operates[id*10+p]){rVol[p]+=W.t1Sold[id*10+p];rRev[p]+=W.t1Rev[id*10+p];rCounts[p]++;}const wP=wVol.map((v,e)=>v?wRev[e]/v:(W.t0Price.filter?0:0));for(let e=0;e<4;e++)if(!wVol[e]){let s=0,n=0;for(let id=0;id<N0;id++)if(T0P[id].elements.includes(E[e])){s+=W.t0Price[id*4+e];n++;}wP[e]=n?s/n:NaN;}const rP=new Float64Array(10);for(let p=0;p<10;p++){if(rVol[p])rP[p]=rRev[p]/rVol[p];else{let s=0,n=0;for(let id=0;id<N1;id++)if(W.t1Operates[id*10+p]&&Number.isFinite(W.t1Price[id*10+p])){s+=W.t1Price[id*10+p];n++;}rP[p]=n?s/n:NaN;}}let wv=wVol[0]+wVol[1]+wVol[2]+wVol[3],wr=wRev[0]+wRev[1]+wRev[2]+wRev[3],rv=0,rr=0;for(let p=0;p<10;p++){rv+=rVol[p];rr+=rRev[p];}return{wVol,wRev,rVol,rRev,wP,rP,wAvg:wv?wr/wv:NaN,rAvg:rv?rr/rv:NaN,wVolume:wv,rVolume:rv};}
function sumArray(a){let s=0;for(let i=0;i<a.length;i++)s+=Number(a[i])||0;return s;}
function hhi(vols){const total=sumArray(vols);if(total<=0)return 0;let h=0;for(let i=0;i<vols.length;i++){const sh=(Number(vols[i])||0)/total;h+=sh*sh;}return h;}
function marketReliability(values,volumes){let total=0,w=0,active=0;for(let i=0;i<values.length;i++){const r=Number(values[i]);if(!Number.isFinite(r))continue;active++;const v=Math.max(0,Number(volumes[i])||0);total+=v;w+=v*r;}return active?(total>0?w/total:values.reduce((a,v)=>a+(Number(v)||0),0)/active):0;}
function markedT0Equity(wP){let total=0;for(let i=0;i<N0;i++){const b=i*4;let inv=0;for(let e=0;e<4;e++)inv+=W.t0Inv[b+e]*(wP[e]||0);total+=W.t0Cash[i]+inv;}return total;}
function cohortAnalytics(m){const cohorts=[];for(let cidx=0;cidx<10;cidx++){const start=cidx*100,end=start+100,pIdx=PI[T1P[cidx].product],product=T1P[cidx].product;let price=0,uc=0,finished=0,raw=0,cash=0,equity=0,made=0,sold=0,revenue=0,cogs=0,rel=0,stability=0,eqCount=0,players=0;for(let id=start;id<end;id++){const b=id*NP+ pIdx,rb=id*4;const stock=W.t1Fin[b]||0,basis=W.t1FinBasis[b]||0;const p=W.t1Price[b];if(Number.isFinite(p)){price+=p;eqCount++;}uc+=W.t1UnitCost[b]||0;finished+=stock;for(let e=0;e<4;e++)raw+=W.raw[rb+e]||0;cash+=W.t1Cash[id]||0;const invVal=(()=>{let v=0;for(let e=0;e<4;e++)v+=(W.raw[rb+e]||0)*(m.wP[e]||0);for(let p2=0;p2<NP;p2++)if(W.t1Operates[id*NP+p2])v+=(W.t1Fin[id*NP+p2]||0)*(m.rP[p2]||0);return v;})();equity+=W.t1Cash[id]+W.t1EqBook[id]+invVal;made+=Math.max(0,(W.t1Fin[b]||0)-(prevT1FinishedCohort[b]||0))+(W.t1Sold[b]||0);sold+=W.t1Sold[b]||0;revenue+=W.t1Rev[b]||0;cogs+=W.t1COGS[b]||0;rel+=W.t1Rel[b]||0;stability+=W.t1PriceStability[b]||0;if(controller[id])players++;prevT1FinishedCohort[b]=W.t1Fin[b]||0;}const marketVol=m.rVol[pIdx]||0;cohorts.push({code:product,name:T1P[cidx].name,firms:end-start,equipment:complexity(product)===1?'Basic':'Compound',avgPrice:eqCount?price/eqCount:NaN,avgUnitCost:uc/(end-start),finished,raw,inventory:finished+raw,cash,equity,made,sold,revenue,cogs,grossProfit:revenue-cogs,margin:revenue?((revenue-cogs)/revenue):0,reliability:rel/(end-start),priceStability:stability/(end-start),marketShare:marketVol?sold/marketVol:0,players});}return cohorts;}
function buildAnalytics(m){
  const t0Inventory=sumArray(W.t0Inv),t0Cash=sumArray(W.t0Cash),t0Sold=sumArray(W.t0Sold),t0Revenue=sumArray(W.t0Revenue);
  const t0Produced=new Array(4).fill(0),t0Vol=[0,0,0,0],t0HHI=[0,0,0,0],t0Rel=[[],[],[],[]];
  for(let i=0;i<N0;i++)for(let e=0;e<4;e++)if(T0P[i].elements.includes(E[e])){const idx=i*4+e;const cur=W.t0Inv[idx]||0,prev=prevT0Inventory[idx]||0,sold=W.t0Sold[idx]||0;t0Produced[e]+=Math.max(0,cur-prev+sold);t0Vol[e]+=sold;t0Rel[e].push(W.t0Rel[idx]);prevT0Inventory[idx]=cur;}
  for(let e=0;e<4;e++){const vols=[];for(let i=0;i<N0;i++)if(T0P[i].elements.includes(E[e]))vols.push(W.t0Sold[i*4+e]||0);t0HHI[e]=hhi(vols);}
  let t1Raw=0,t1Finished=0,t1Cash=0,t1Sold=0,t1Revenue=0,t1COGS=0,t1Made=0,t1Equity=0,activeFirms=0,players=0,relWeighted=0,relN=0;
  for(let id=0;id<N1;id++){const rb=id*4;let raw=0,finished=0,eqv=W.t1Cash[id]+W.t1EqBook[id];for(let e=0;e<4;e++){raw+=W.raw[rb+e]||0;eqv+=(W.raw[rb+e]||0)*(m.wP[e]||0);}t1Raw+=raw;t1Finished+=finished;t1Cash+=W.t1Cash[id]||0; if(W.t1Controller[id])players++;let any=false;for(let p=0;p<NP;p++)if(W.t1Operates[id*NP+p]){const idx=id*NP+p,fin=W.t1Fin[idx]||0;finished+=fin;eqv+=fin*(m.rP[p]||0);t1Sold+=W.t1Sold[idx]||0;t1Revenue+=W.t1Rev[idx]||0;t1COGS+=W.t1COGS[idx]||0;t1Made+=Math.max(0,fin-(prevT1Finished[idx]||0))+(W.t1Sold[idx]||0);prevT1Finished[idx]=fin;relWeighted+=W.t1Rel[idx]||0;relN++;any=true;}if(any)activeFirms++;t1Finished+=finished;t1Equity+=eqv;}
  const potential=sumArray(W.potential),active=sumArray(W.active),fulfilled=sumArray(W.fulfilled),priceLost=sumArray(W.priceLost),stockUnmet=sumArray(W.stockUnmet);const orderTotal=sourceState.activeOrders,fulfilledOrders=sourceState.fulfilledOrders;
  const cohort=cohortAnalytics(m);
  const latest={tick,wholesaleAvg:m.wAvg,retailAvg:m.rAvg,wVolume:m.wVolume,rVolume:m.rVolume,t0Inventory,t1Inventory:t1Raw+t1Finished,t0Equity:markedT0Equity(m.wP),t1Equity,t0Cash,t1Cash,retailPotential:potential,retailActive:active,retailFulfilled:fulfilled,priceLost,stockUnmet,t1GrossProfit:t1Revenue-t1COGS,avgT0Reliability:t0Rel.flat().length?t0Rel.flat().reduce((a,v)=>a+(Number(v)||0),0)/t0Rel.flat().length:0,avgT1Reliability:relN?relWeighted/relN:0};
  analyticsHistory.push(latest);if(analyticsHistory.length>240)analyticsHistory.shift();
  return {cohort,latest,t0Inventory,t0Cash,t0Sold,t0Revenue,t0Equity:markedT0Equity(m),t0Produced,t0Vol,t0HHI,t1Raw,t1Finished,t1Cash,activeFirms,players,t1Made,t1Sold,t1Revenue,t1COGS,t1Equity,potential,active,fulfilled,priceLost,stockUnmet,orderTotal,fulfilledOrders,unitFillRate:active?fulfilled/active:0,orderFillRate:orderTotal?fulfilledOrders/orderTotal:0,priceLossShare:potential?priceLost/potential:0,stockUnmetShare:active?stockUnmet/active:0,retailRevenue:m.rRev.reduce((a,v)=>a+(v||0),0),difficultyMean:(W.difficulty[0]+W.difficulty[1]+W.difficulty[2]+W.difficulty[3])/4,difficultyMin:Math.min(...W.difficulty),difficultyMax:Math.max(...W.difficulty)};
}
function companyDetail(tier,id){id=Math.max(0,id|0);if(tier==='T0'){const co=T0P[id];if(!co)return null;const elements=[];let inventory=0,prod=0,sold=0,revenue=0,equity=W.t0Cash[id];for(const e of E){if(!co.elements.includes(e))continue;const i=EI[e],idx=id*4+i,stock=W.t0Inv[idx]||0,invVal=stock*(lastWholesalePrice(i)||0);inventory+=stock;prod+=Math.max(0,stock-(prevT0Inventory[idx]||0))+(W.t0Sold[idx]||0);sold+=W.t0Sold[idx]||0;revenue+=W.t0Revenue[idx]||0;equity+=invVal;elements.push({element:e,stock,cost:W.t0Cost[idx],price:W.t0Price[idx],production:lastTickT0Produced[idx]||0,sold:W.t0Sold[idx]||0,revenue:W.t0Revenue[idx]||0,reliability:W.t0Rel[idx]||0,stability:W.t0Stability[idx]||0,reliabilityAttempts:t0RelAttemptsCount(id,i)});}return {tier:'T0',id,name:co.name,elements:co.elements,cash:W.t0Cash[id],inventory,equity,capacity:cfg.capacity,targetInventory:cfg.targetInventory,maxInventory:cfg.maxInventory,status:'ACTIVE',elementData:elements};}const piBase=T1P[Math.floor(id/100)];if(!piBase)return null;const raw=[];for(const e of E){const i=EI[e],idx=id*4+i;raw.push({element:e,stock:W.raw[idx]||0,basis:W.rawBasis[idx]||0,lastBuy:Number.isFinite(W.t1LastBuy[idx])?W.t1LastBuy[idx]:null,inputNeed:W.t1InputNeed[idx]||0,purchaseRequest:W.t1PurchaseReq[idx]||0,preferredSupplier:W.preferredWholesale[id*4+i]??-1});}const products=[];let inv=0,eqv=W.t1Cash[id]+W.t1EqBook[id],made=0,sold=0,revenue=0,cogs=0;for(let p=0;p<NP;p++)if(W.t1Operates[id*NP+p]){const idx=id*NP+p,fin=W.t1Fin[idx]||0;inv+=fin;eqv+=fin*(marketAverages().rP[p]||0);made+=Math.max(0,fin-(prevT1Finished[idx]||0))+(W.t1Sold[idx]||0);sold+=W.t1Sold[idx]||0;revenue+=W.t1Rev[idx]||0;cogs+=W.t1COGS[idx]||0;products.push({product:P[p].code,price:W.t1Price[idx],unitCost:W.t1UnitCost[idx],finished:fin,finishedBasis:W.t1FinBasis[idx]||0,salesEMA:W.t1SalesEMA[idx]||0,made:lastTickT1Made[idx]||0,sold:W.t1Sold[idx]||0,revenue:W.t1Rev[idx]||0,cogs:W.t1COGS[idx]||0,reliability:W.t1Rel[idx]||0,priceStability:W.t1PriceStability[idx]||0,reliabilityAttempts:t1RelAttemptsCount(id,p)});}for(const x of raw)inv+=x.stock;for(const e of E)eqv+=W.raw[id*4+EI[e]]*(marketAverages().wP[EI[e]]||0);return {tier:'T1',id,name:piBase.name+' '+String(id%100+1).padStart(3,'0'),native:piBase.product,controller:controller[id]?'PLAYER':'BOT',online:!!online[id],cash:W.t1Cash[id],equipment:[...equipment[id]],equipmentBookValue:W.t1EqBook[id],inventory:inv,equity:eqv,raw,products,made,sold,revenue,cogs,grossProfit:revenue-cogs,reliability:products.length?products.reduce((a,x)=>a+x.reliability,0)/products.length:0};}
function lastWholesalePrice(i){let s=0,n=0;for(let id=0;id<N0;id++)if(T0P[id].elements.includes(E[i])){s+=W.t0Price[id*4+i];n++;}return n?s/n:NaN;}
function t0RelAttemptsCount(id,i){return W.t0RelAttempts[id*4+i]||0}
function t1RelAttemptsCount(id,p){return W.t1RelAttempts[id*NP+p]||0}
function watchedDetails(){const out={};for(const id of watchedCompanies.T0)if(id>=0&&id<N0)out['T0:'+id]=companyDetail('T0',id);for(const id of watchedCompanies.T1)if(id>=0&&id<N1)out['T1:'+id]=companyDetail('T1',id);return out;}
function companySummariesT0(m){const out=[];for(let id=0;id<N0;id++){const prof=T0P[id];let inv=0,prod=0,sold=0,rev=0,rel=0,n=0,eq=W.t0Cash[id];for(let e=0;e<NE;e++)if(prof.elements.includes(E[e])){const idx=id*4+e;const stock=W.t0Inv[idx]||0;inv+=stock;prod+=Math.max(0,stock-(prevT0Inventory[idx]||0))+(W.t0Sold[idx]||0);sold+=W.t0Sold[idx]||0;rev+=W.t0Revenue[idx]||0;rel+=W.t0Rel[idx]||0;n++;eq+=stock*(m.wP[e]||0);}out.push({id,name:prof.name,elements:[...prof.elements],cash:W.t0Cash[id],inventory:inv,equity:eq,production:prod,sold,revenue:rev,avgPrice:n?prof.elements.reduce((a,e)=>a+W.t0Price[id*4+EI[e]],0)/n:NaN,reliability:n?rel/n:0});}return out;}
function productReadyStock(pi){let s=0;for(let id=0;id<N1;id++)s+=W.t1Fin[id*NP+pi]||0;return s;}
function productSupplyCapacity(pi){let cap=0;const unitCap=pi<4?cfg.basicEquipmentCapacity:cfg.compoundEquipmentCapacity;for(let id=0;id<N1;id++)if(W.t1Operates[id*NP+pi])cap+=unitCap;return cap;}
function publish(){const m=marketAverages(),now=performance.now(),elapsed=Math.max(.001,(now-lastReportAt)/1000),intervalTicks=tick-lastReportTick;const tps=intervalTicks/elapsed;lastReportAt=now;lastReportTick=tick;const sid=Math.max(0,Math.min(N1-1,selectedId)),scode=T1P[Math.floor(sid/100)].product,spi=PI[scode];const analytics=buildAnalytics(m);const companies=[];for(let id=0;id<N1;id++){const pi=PI[T1P[Math.floor(id/100)].product],b=id*10;let raw=0,fin=0,totalSold=0,totalRevenue=0,totalCOGS=0,totalMade=0,rel=0,relN=0;for(let e=0;e<4;e++)raw+=W.raw[id*4+e]||0;for(let p=0;p<NP;p++)if(W.t1Operates[id*NP+p]){fin+=W.t1Fin[id*NP+p]||0;totalSold+=W.t1Sold[id*NP+p]||0;totalRevenue+=W.t1Rev[id*NP+p]||0;totalCOGS+=W.t1COGS[id*NP+p]||0;totalMade+=Math.max(0,(W.t1Fin[id*NP+p]||0)-(prevT1Finished[id*NP+p]||0))+(W.t1Sold[id*NP+p]||0);rel+=W.t1Rel[id*NP+p]||0;relN++;}companies.push({id,name:T1P[Math.floor(id/100)].name+' '+String(id%100+1).padStart(3,'0'),native:T1P[Math.floor(id/100)].product,controller:controller[id]?'PLAYER':'BOT',equipment:[...equipment[id]],price:W.t1Price[b+pi],raw,finished:fin,inventory:raw+fin,cash:W.t1Cash[id],equity:W.t1Cash[id]+W.t1EqBook[id]+(()=>{let v=0;for(let e=0;e<4;e++)v+=(W.raw[id*4+e]||0)*(m.wP[e]||0);for(let p=0;p<NP;p++)if(W.t1Operates[id*NP+p])v+=(W.t1Fin[id*NP+p]||0)*(m.rP[p]||0);return v;})(),made:totalMade,sold:totalSold,revenue:totalRevenue,grossProfit:totalRevenue-totalCOGS,reliability:relN?rel/relN:0});}const productStats=P.map((p,i)=>{const suppliers=[];for(let id=0;id<N1;id++)if(W.t1Operates[id*NP+i])suppliers.push({id,vol:W.t1Sold[id*NP+i]||0,rel:W.t1Rel[id*NP+i]||0});return {code:p.code,name:p.name,retailPrice:m.rP[i],volume:m.rVol[i],revenue:m.rRev[i],supplyCapacity:productSupplyCapacity(i),readyStock:productReadyStock(i),potential:W.potential[i],active:W.active[i],fulfilled:W.fulfilled[i],priceLost:W.priceLost[i],stockUnmet:W.stockUnmet[i],hhi:hhi(suppliers.map(x=>x.vol)),reliability:marketReliability(suppliers.map(x=>x.rel),suppliers.map(x=>x.vol)),fillRate:W.active[i]?W.fulfilled[i]/W.active[i]:0};});const elementStats=E.map((e,i)=>({code:['W','E','F','A'][i],price:m.wP[i],volume:m.wVol[i],difficulty:W.difficulty[i],hhi:analytics.t0HHI[i],reliability:marketReliability(t0RelSafe(i),t0VolsFor(i))}));
  lastSnapshot={tick,month,tps,mode,targetTPS,difficulty:{Water:W.difficulty[0],Earth:W.difficulty[1],Fire:W.difficulty[2],Air:W.difficulty[3]},wholesaleAvg:m.wAvg,retailAvg:m.rAvg,wholesaleVolume:m.wVolume,retailVolume:m.rVolume,retailOrders:analytics.orderTotal,fulfilledOrders:analytics.fulfilledOrders,elements:elementStats,products:productStats,cohorts:analytics.cohort,t0Companies:companySummariesT0(m),analyticsHistory,tiers:{t0:{inventory:analytics.t0Inventory,cash:analytics.t0Cash,equity:analytics.t0Equity,sold:analytics.t0Sold,revenue:analytics.t0Revenue,productionByElement:analytics.t0Produced,hhi:analytics.t0HHI,reliability:analytics.latest.avgT0Reliability},t1:{inventory:analytics.latest.t1Inventory,raw:analytics.t1Raw,finished:analytics.t1Finished,cash:analytics.t1Cash,equity:analytics.t1Equity,made:analytics.t1Made,sold:analytics.t1Sold,revenue:analytics.t1Revenue,cogs:analytics.t1COGS,grossProfit:analytics.t1Revenue-analytics.t1COGS,activeFirms:analytics.activeFirms,players:analytics.players,reliability:analytics.latest.avgT1Reliability},t2:{potential:analytics.potential,active:analytics.active,fulfilled:analytics.fulfilled,priceLost:analytics.priceLost,stockUnmet:analytics.stockUnmet,orders:analytics.orderTotal,fulfilledOrders:analytics.fulfilledOrders,unitFillRate:analytics.unitFillRate,orderFillRate:analytics.orderFillRate,priceLossShare:analytics.priceLossShare,stockUnmetShare:analytics.stockUnmetShare,revenue:analytics.retailRevenue}},companies,selected:{id:sid,name:T1P[Math.floor(sid/100)].name+' '+String(sid%100+1).padStart(3,'0'),native:scode,controller:controller[sid]?'PLAYER':'BOT',online:!!online[sid],price:W.t1Price[sid*10+spi],cash:W.t1Cash[sid],finished:W.t1Fin[sid*10+spi],inventory:rawSum(sid)+finSum(sid),eqBook:W.t1EqBook[sid],equipment:[...equipment[sid]],reliability:W.t1Rel[sid*10+spi]},engine:'source',expandedDetails:watchedDetails()};self.postMessage({type:'snapshot',data:lastSnapshot});}
function t0RelSafe(ei){const v=[];for(let i=0;i<N0;i++)if(T0P[i].elements.includes(E[ei]))v.push(W.t0Rel[i*4+ei]||0);return v}
function t0VolsFor(ei){const v=[];for(let i=0;i<N0;i++)if(T0P[i].elements.includes(E[ei]))v.push(W.t0Sold[i*4+ei]||0);return v}

function runLoop(){if(!running)return;if(mode==='max'){const start=performance.now();while(running&&performance.now()-start<45)step();publish();timer=setTimeout(runLoop,0);return;}step();publish();timer=setTimeout(runLoop,500);}
self.onmessage=async event=>{const message=event.data;try{
  if(message.type==='init'){initEngine();reset(message.cfg||defaultCfg());return;}
  if(message.type==='run'){running=true;mode=message.mode||'fixed';runLoop();return;}
  if(message.type==='pause'){running=false;if(timer)clearTimeout(timer);publish();return;}
  if(message.type==='step'){if(!running){step();publish();}return;}
  if(message.type==='reset'){running=false;if(timer)clearTimeout(timer);reset(message.cfg||defaultCfg());return;}
  if(message.type==='applyConfig'){updateLive(message.cfg);publish();return;}
  if(message.type==='select'){selectedId=Math.max(0,Math.min(N1-1,message.id|0));publish();return;}
  if(message.type==='companyDetail'){self.postMessage({type:'companyDetail',data:companyDetail(message.tier==='T0'?'T0':'T1',message.id|0)});return;}
  if(message.type==='watchCompanies'){watchedCompanies.T0=new Set((message.watches?.T0||[]).map(x=>x|0).filter(x=>x>=0&&x<N0));watchedCompanies.T1=new Set((message.watches?.T1||[]).map(x=>x|0).filter(x=>x>=0&&x<N1));publish();return;}
  if(message.type==='player'){const id=message.id;selectedId=id;controller[id]=message.controller==='PLAYER'?1:0;online[id]=message.online?1:0;W.t1Controller[id]=controller[id];const index=id*10+PI[message.code];if(controller[id]&&Number.isFinite(message.price)){playerPrices[id][message.code]=quantR(message.price);W.playerPrice[index]=playerPrices[id][message.code];}publish();return;}
  if(message.type==='buyEquipment'){const id=message.id,code=message.code,product=PB[code];if(controller[id]!==1||!product||equipment[id].includes(code)){self.postMessage({type:'equipmentResult',ok:false,msg:'Only PLAYER-controlled companies can buy new equipment.'});return;}if(W.t1Cash[id]+1e-9<product.equipmentPrice){self.postMessage({type:'equipmentResult',ok:false,msg:'Insufficient cash.'});return;}W.t1Cash[id]-=product.equipmentPrice;W.t1EqBook[id]+=product.equipmentPrice;eqBook[id]+=product.equipmentPrice;equipment[id].push(code);const index=id*10+PI[code],inputCost=Object.entries(product.inputs).reduce((total,[element,ratio])=>total+lastFiniteWholesale(element)*ratio,0);W.t1Operates[index]=1;W.t1UnitCost[index]=inputCost+cfg.manufacturingCostPerUnit;W.t1Rel[index]=.5;W.t1Price[index]=quantR(W.t1UnitCost[index]*(1+markup(code,cfg)),W.t1UnitCost[index]*(1+cfg.minMargin));W.t1PrevPrice[index]=W.t1Price[index];publish();self.postMessage({type:'equipmentResult',ok:true});}
}catch(error){self.postMessage({type:'error',message:error?.stack||String(error)});}};
function lastFiniteWholesale(e){const ei=EI[e];let best=Infinity;for(let i=0;i<N0;i++)if(T0P[i].elements.includes(e))best=Math.min(best,W.t0Price[i*4+ei]);return Number.isFinite(best)?best:cfg.baseCost;}
