'use strict';
const assert=require('node:assert/strict');
const {createWorker}=require('./worker_harness');
const w=createWorker({t2FirmCount:1000,endUserCount:20000});const M=w.model;
assert.equal(M.calendarAt(16).tickHex,'0x10');
assert.equal(M.calendarAt(172800).tickHex,'0x2A300');
assert.equal(M.TIME.ticksPerAge,480*12*30);
assert.equal(M.calendarAt(172799).ageDecimal,'0');
assert.equal(M.calendarAt(172800).ageDecimal,'1');
assert.equal(M.calendarAt(172800*16).ageDecimal,'16');
assert.ok(Math.abs((1+M.AGE_EQUITY_GROWTH)**172800-2)<1e-9);
assert.equal(M.T2_CATALOGUE.length,420);assert.equal(M.T2_PRODUCTS.length,200);assert.equal(M.T2_UNINVENTED_PRODUCTS.length,220);
const active=new Set(M.T2_PRODUCTS.map(p=>p.recipeKey));
assert.ok(M.T2_UNINVENTED_PRODUCTS.every(p=>!active.has(p.recipeKey)));
for(let sector=0;sector<10;sector++)for(const c of [3,4,5])assert.equal(M.T2_PRODUCTS.filter(p=>p.sectorIndex===sector&&p.complexity===c).length,M.INVENTED_PER_COMPLEXITY[c]);
assert.ok(M.T2_SECTOR_WEIGHTS.every(x=>x===1));
for(const p of M.T2_UNINVENTED_PRODUCTS)assert.equal(M.T2_PRODUCT_BY_CODE[p.code],undefined,'Uninvented equipment is unavailable');
for(let t=0;t<36;t++)w.step();const s=w.snapshot();
assert.ok(s.tier2Industries.every(x=>x.products===20));
assert.deepEqual(s.invention,{possible:420,invented:200,reserved:220});
assert.ok(s.tier2Products.every(p=>M.T2_PRODUCT_BY_CODE[p.code]));
console.log('Age boundaries, 200 invented markets, 220 unavailable recipes and symmetric sector slots: ok');
